import {
	InputData,
	jsonInputForTargetLanguage,
	quicktype,
} from "quicktype-core";

export type QuicktypeOptions = {
	topLevelName: string;
};

export const generateTypesFromJson = async (
	json: unknown,
	options: QuicktypeOptions,
): Promise<string> => {
	const jsonInput = jsonInputForTargetLanguage("ts");
	await jsonInput.addSource({
		name: options.topLevelName,
		samples: [JSON.stringify(json)],
	});

	const inputData = new InputData();
	inputData.addInput(jsonInput);

	const result = await quicktype({
		inputData,
		lang: "ts",
		rendererOptions: {
			"just-types": "true",
			"prefer-types": "true",
			"no-enums": "true",
			"no-date-times": "true",
			"no-uuids": "true",
		},
	});

	const output = `${result.lines.join("\n").trimEnd()}\n`;
	if (!output.includes(`export type ${options.topLevelName}`)) {
		throw new Error("Expected type alias was not generated by quicktype.");
	}

	return output;
};
