import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import typia from "typia";

import type { SearchRetrieveResponse } from "../src/types/example_response";

const schemaDir = resolve("src", "schema");
const collectionPath = resolve(schemaDir, "example_response.collection.json");
const schemaPath = resolve(schemaDir, "example_response.schema.json");
const rootName = "SearchRetrieveResponse";

mkdirSync(schemaDir, { recursive: true });

const collection = typia.json.schemas<[SearchRetrieveResponse], "3.1">();

writeFileSync(collectionPath, `${JSON.stringify(collection, null, 2)}\n`);

const components = collection.components?.schemas;
if (!components || typeof components !== "object") {
	throw new Error("Schema components were not generated by typia.");
}

const rootSchema = (components as Record<string, unknown>)[rootName];
if (!rootSchema || typeof rootSchema !== "object") {
	throw new Error(`Root schema not found: ${rootName}`);
}

const normalizeRefs = (value: unknown): unknown => {
	if (Array.isArray(value)) {
		return value.map((entry) => normalizeRefs(entry));
	}

	if (!value || typeof value !== "object") {
		return value;
	}

	const entries = Object.entries(value as Record<string, unknown>);
	const normalized: Record<string, unknown> = {};
	for (const [key, entry] of entries) {
		if (key === "$ref" && typeof entry === "string") {
			normalized[key] = entry.replace("#/components/schemas/", "#/$defs/");
			continue;
		}

		normalized[key] = normalizeRefs(entry);
	}

	return normalized;
};

const normalizedDefs = normalizeRefs(components) as Record<string, unknown>;
const normalizedRoot = normalizeRefs(rootSchema) as Record<string, unknown>;

const outputSchema: Record<string, unknown> = {
	$schema: "https://json-schema.org/draft/2020-12/schema",
	...normalizedRoot,
	$defs: normalizedDefs,
};

if (!outputSchema.title) {
	outputSchema.title = rootName;
}

writeFileSync(schemaPath, `${JSON.stringify(outputSchema, null, 2)}\n`);
