import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

const inputPath = resolve("openspec", "example_response.json");
const outputPath = resolve("src", "types", "example_response.ts");
const binPath = resolve("node_modules", ".bin", "quicktype");

if (!existsSync(inputPath)) {
	throw new Error(`Input JSON not found: ${inputPath}`);
}

mkdirSync(resolve("src", "types"), { recursive: true });

execFileSync(
	binPath,
	[
		"--lang",
		"ts",
		"--src-lang",
		"json",
		"--just-types",
		"--prefer-types",
		"--no-enums",
		"--no-date-times",
		"--no-uuids",
		"--top-level",
		"SearchRetrieveResponse",
		"--out",
		outputPath,
		inputPath,
	],
	{ stdio: "inherit" },
);

const output = readFileSync(outputPath, "utf-8");
if (!output.includes("export type SearchRetrieveResponse")) {
	throw new Error("Expected type alias was not generated by quicktype.");
}
