// This file is auto-generated by @hey-api/openapi-ts

export { getSru, type Options } from './sdk.gen';
export type { ClientOptions, Dc, GetSruData, GetSruResponse, GetSruResponses, Record, RecordData, Records, SearchRetrieveResponse, SearchRetrieveResponseClass } from './types.gen';
