// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * SearchRetrieveResponse
 */
export type SearchRetrieveResponse = {
    searchRetrieveResponse: SearchRetrieveResponseClass;
};

export type SearchRetrieveResponseClass = {
    version: number;
    numberOfRecords: number;
    nextRecordPosition: number;
    records: Records;
};

export type Records = {
    record: Array<Record>;
};

export type Record = {
    recordSchema: 'info:srw/schema/1/dc-v1.1';
    recordPacking: 'string';
    recordData: RecordData;
    recordPosition: number;
};

export type RecordData = {
    dc: Dc;
};

export type Dc = {
    title: string;
    subject?: Array<string>;
    language: Language;
    attr_schemaLocation: string;
    creator?: string;
};

export type Language = 'ja' | 'jpn';
