// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * SearchRetrieveResponse
 */
export type SearchRetrieveResponse = {
    searchRetrieveResponse: SearchRetrieveResponseClass;
};

export type SearchRetrieveResponseClass = {
    version: number;
    numberOfRecords: number;
    nextRecordPosition: number;
    records: Records;
};

export type Records = {
    record: Array<Record>;
};

export type Record = {
    recordSchema: string;
    recordPacking: string;
    recordData: RecordData;
    recordPosition: number;
};

export type RecordData = {
    dc: Dc;
};

export type Dc = {
    title: string;
    subject?: Array<string>;
    language: string;
    attr_schemaLocation: string;
    creator?: string;
};

export type SearchRetrieveData = {
    body?: never;
    path?: never;
    query: {
        /**
         * searchRetrieve 固定
         */
        operation: 'searchRetrieve';
        /**
         * 取得件数の固定値
         */
        maximumRecords: 10;
        /**
         * title もしくは isbn の単一条件
         */
        query: string;
    };
    url: '/api/sru';
};

export type SearchRetrieveResponses = {
    /**
     * OK
     */
    200: SearchRetrieveResponse;
};

export type SearchRetrieveResponse2 = SearchRetrieveResponses[keyof SearchRetrieveResponses];
