// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * SearchRetrieveResponse
 */
export type SearchRetrieveResponse = {
    searchRetrieveResponse: SearchRetrieveResponseClass;
};

export type SearchRetrieveResponseClass = {
    version: number;
    numberOfRecords: number;
    records: Records;
};

export type Records = {
    record: Array<Record>;
};

export type Record = {
    recordSchema: string;
    recordPacking: string;
    recordData: RecordData;
    recordPosition: number;
};

export type RecordData = {
    dc: Dc;
};

export type Dc = {
    title: string;
    creator?: string;
    subject?: Array<string>;
    description?: string;
    language?: string;
    attr_schemaLocation: string;
};

export type GetSruData = {
    body?: never;
    path?: never;
    query: {
        operation: string;
        query: string;
        maximumRecords?: number;
    };
    url: '/api/sru';
};

export type GetSruResponses = {
    /**
     * OK
     */
    200: SearchRetrieveResponse;
};

export type GetSruResponse = GetSruResponses[keyof GetSruResponses];
